name: cloudwalk_gps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.1
  dio: ^5.4.2
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
